project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - lessons/*.qmd
  resources:
    - .nojekyll

website:
  title: "R for Novices - Gapminder Lessons"
  navbar:
    left:
      - href: index.html
        text: Home
      - text: Introduction
        menu:
          - text: Intro to R
            href: lessons/rstudio-intro.html
          - text: Projects
            href: lessons/project-management.html
          - text: Help
            href: lessons/seeking-help.html
      - href: lessons/data-structures.html
        text: Data Structures
      - href: lessons/exploring_dataframes.html
        text: Data Frames
      - href: lessons/data_subsetting.html
        text: Subsetting
      - href: lessons/control_flow.html
        text: Control Flow
      - href: lessons/ggplot2.html
        text: ggplot2
      - href: lessons/vectorization.html
        text: Vectorization
      - href: lessons/functions.html
        text: Functions
      - href: lessons/writing_data.html
        text: Write Data
      - href: lessons/dplyr.html
        text: dplyr
      - href: lessons/knitr-markdown.html
        text: R Markdown
      - href: lessons/writing-good-software.html
        text: Style
    right:
      - icon: github
        href: https://github.com/samuelbharti/sw-r-novice-gapminder-lessons

metadata-files:
  - lessons/_metadata.yml

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
    css: custom.css
