project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - lessons/*.qmd
  resources:
    - .nojekyll

website:
  title: "R for Novices - Gapminder Lessons"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: lessons/exploring_dataframes.html
        text: Exploring Data Frames
      - href: lessons/data_subsetting.html
        text: Subsetting Data
      - href: lessons/functions.html
        text: Functions
      - href: lessons/writing_data.html
        text: Writing Data
    right:
      - icon: github
        href: https://github.com/samuelbharti/sw-r-novice-gapminder-lessons

metadata-files:
  - lessons/_metadata.yml

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
    css: custom.css
